#%RAML 1.0
title: CustomerDetails
baseUri: http://api.kamini.customerdetails.com/{version}
version: v1
#baseUriParameters:
#  apiversion:
#    displayName: API Version
#    type: string
#    enum: ["v1"]
  #resources
mediaType: application/json
/customerId:
 get:
   queryParameters:
    customerId:
     displayName: Customer ID
     type: string
     description: Customer unique ID
     example: 1875522DRF
     required: true
   responses:
        200:
          description: Sychronous response for get request
          body:
            application/json:
              schema: !include json/user-get-cust-response-schema.json
              
              
              